runtime: python
env: flex
#PORT is previously defined
entrypoint: gunicorn -b :$PORT flask_api:app

runtime_config:
    python_version: 3

manual_scaling:
    instances: 1
resources:
    cpu: 2
    memory_gb: 1.4
    disk_size_gb: 10
